// Typelizer digest 2162fdbfe4b2635e5ff776aa01604724
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Proposal = {
  id: string;
  cfp_id: string | null;
  title: string | null;
  details: string | null;
  abstract: string | null;
  pitch: string | null;
  track: "oss" | "scale" | "general" | null;
  status: "draft" | "submitted" | "accepted" | "rejected" | "waitlisted" | "confirmed" | "declined";
  submitted_at: string | null;
  can_edit: boolean;
}

export default Proposal;
